version: '3.8'

services:
  nginx:
    image: nginx:1.21.3
    container_name: nginx
    restart: unless-stopped
    volumes:
      - ./app:/var/www
      - ./services/nginx/conf.d:/etc/nginx/conf.d
      - ./services/nginx/logs:/var/log/nginx
    ports:
      - 80:80
    depends_on:
      - php
  php:
    build:
      context: ./services/php
      args:
        USER: dm-docker
        UID: 1000
    container_name: php
    restart: unless-stopped
    volumes:
      - ./app:/var/www
  mysql:
    image: mysql:8
    container_name: mysql
    restart: unless-stopped
    volumes:
      - ./services/mysql/data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
  phpmyadmin:
    image: phpmyadmin:5.1.1
    restart: unless-stopped
    container_name: phpmyadmin
    ports:
      - 8080:80
    environment:
      - PMA_HOST
    depends_on:
      - mysql
